<?php
/**
 * @author Maxim Cherednyk <maks757q@gmail.com, +380639960375>
 */

namespace bl\progress;


use bl\progress\behaviors\Validate;
use bl\progress\components\ValidateProgress;
use Yii;
use yii\base\Component;

/**
 * @method validateOne(string $key, int $user_id)
 * @method validate(string $key)
*/

class Progress extends Component
{
    public $honors = [];
    public $validatorClass;
    public $imageBasePath = '@webroot/progressImages/progress';

    public function behaviors()
    {
        return [
            'validate' => [
                'class' => Validate::class
            ]
        ];
    }


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->registerDependencies();
    }

    private function registerDependencies()
    {
        \Yii::$container->set('bl\progress\interfaces\IProgressValidator',
            $this->validatorClass);
    }
}