<?php
/**
 * @author Maxim Cherednyk <maks757q@gmail.com, +380639960375>
 */

namespace bl\progress;


use yii\base\Component;
use yii\helpers\Console;

class Progress extends Component
{
    public function init()
    {
        die('test');
        parent::init(); // TODO: Change the autogenerated stub
    }

}